// Teste requsições REST da collection Usuários

@baseURL = https://projeto-api-nu.vercel.app/api/usuarios

// POST - Insere novo registro
POST {{baseURL}}
Content-Type: application/json

{
    "nome": "Ednaldo Pereira",
    "email": "ednaldo.pereira@gmail.com",
    "senha": "Senha@123",
    "ativo": true,
    "tipo": "Cliente",
    "avatar": "https://ui-avatars.com/api/?name=Ednaldo+Pereira"
}


###
// POST - Efetua o Login - JWT é salvo automaticamente
// com Set-Cookie header. Cookie HTTP-Only
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "ednaldo.pereira@gmail.com",
    "senha": "Senha@123"
}


###
// POST - Efetua o Logout - JWT é excluído automaticamente
// com Set-Cookie header.
POST {{baseURL}}/logout
Content-Type: application/json


###
// GET - Valida o Token dos Cookies
GET {{baseURL}}/validateToken
Content-Type: application/json


###
// GET - Lista os usuários
GET {{baseURL}}
Content-Type: application/json


###
// DELETE - Remove um usuário pelo ID
DELETE {{baseURL}}/655508edbbeb4a965b42dd9c
Content-Type: application/json


###
// PUT - Update usuário pelo ID
PUT {{baseURL}}/655eb2798aae7c43fb99632a
Content-Type: application/json

{
    "nome": "bbbb",
    "email": "aaa@aaa.com",
    "senha": "Senha@123",
    "ativo": true,
    "tipo": "Cliente",
    "avatar": "https://ui-avatars.com/api/?name=Ednaldo+Pereira"
}